### PR TITLE
feat: tpl for image values

### PR DESCRIPTION
**Pull request by thecampagnards**
Hello,
In some deployments I need to do tpl for image.tag
like:
```yaml
image:
  tag: "{{ .Chart.Version }}"
```
I think this is a useful case
Thx !

### CODE REVIEW

**Comment by thecampagnards** [comment]
I will update the author when I will have a computer

**Comment by thecampagnards** [comment]
Up ? 😄

**Comment by kilianpaquier** [comment]
Hey ! I'm interested with this feature, can someone take a look ?

**Comment by aabouzaid** [comment]
Sorry @thecampagnards I don't follow the project recently.
But it looks good to me, thank you :rocket:  (the error on the CI related to cluster creation I might look into it later).

**Pull request merged**
