### PR TITLE
Feat: Support custom labels

### PR DESCRIPTION
**Pull request by patrickegli**
Add option to specify labels that are added to all deployed objects

We need this to comply to the company's kyverno policies that require some specific labels to be present on each deployed application.

### CODE REVIEW

**Comment by patrickegli** [comment]
@thecampagnards Any chance getting this merged and released soon?

**Comment by thecampagnards** [comment]
> @thecampagnards Any chance getting this merged and released soon?

Hello yes sorry I will check it and release it soon

**Review by thecampagnards — APPROVED** [review]

**Comment by patrickegli** [comment]
@thecampagnards Thanks for merging. Can we expect a release soon?

**Comment by thecampagnards** [comment]
> @thecampagnards Thanks for merging. Can we expect a release soon?

Good feature available inside the 7.6.5, https://github.com/camunda-community-hub/camunda-7-community-helm/releases/tag/camunda-bpm-platform-7.6.5

**Pull request merged**
